package ishpal.loginregister;

import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;


public class Login extends ActionBarActivity implements View.OnClickListener {

    Button bLogin;
    EditText etUsername, etPassword;
    TextView tvRegisterLink;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        etUsername= (EditText) findViewById(R.id.etUsername);   // looks through activity xml to find the view that has an id called etUsername and it casts it to EditText and assigns it to etUsername variable
        etPassword= (EditText) findViewById(R.id.etPassword);
        bLogin = (Button) findViewById(R.id.bLogin);
        tvRegisterLink= (TextView) findViewById(R.id.tvRegisterLink); // for when the register link is clicked on the login page

        bLogin.setOnClickListener(this);        // for this to handle click events generated by its views
        tvRegisterLink.setOnClickListener(this);
    }


    // When login is clicked, this method is notified
    @Override
    public void onClick(View v) {
        switch (v.getId()) {      // gets id of the view which notifies this onClick method and if the login button notifies the method then we break
            case R.id.bLogin:
                break;

            case R.id.tvRegisterLink:
                startActivity(new Intent(this, Register.class));
                break;
        }
    }
}
